### ISSUE TITLE
Archive of THOMAS

### ISSUE THREAD

**Issue by DanielSchuman** [usgpo/bill-status#12]
This probably is not the right place to raise the issue, but I want to suggest that the HTML pages for THOMAS be archived before the website is shut down (in whatever way it is shut down). 

A good example is the web harvest performed by the National Archives of Congressional sites (see http://www.webharvest.gov/). It appears the robot.txt directive on THOMAS.gov has prevented the Wayback Machine from archiving THOMAS. At a minimum, we should have a copy of it as it is at its final state, ideally in one that is crawlable.

**Comment by llaplant** [comment]
Yes, at [THOMAS web archive](http://webarchive.loc.gov/all/*/thomas.loc.gov). The archive is a record, like a snapshot, that shows the site as it was in 2013 and earlier. Since 2012, development efforts shifted from THOMAS to Congresss.gov. An archive does not provide search functionality nor current data. It does provide a historical record of the look and feel of the site. 
Congress.gov provides comparable and improved functionality. Prior to THOMAS retirement all data will be available from Congress.gov. The last two data sets to be transferred from THOMAS to Congress.gov will be transferred in June 2016. Those data sets are: [Congressional Record daily edition issues for 1989-1994](https://www.congress.gov/about/coverage-dates#note3) and Senate Executive and Other Communications for 1979-1986. [Coverage Dates for Legislative Information](https://www.congress.gov/about/coverage-dates) is a directory of Congress.gov collections and data sets.
Help guides, documentation, and finding aids have also been migrated to Congress.gov. The chart below provides Congress.gov URLs for popular THOMAS pages. Contact us if you need help finding the new URL for other pages.
The project to replace THOMAS with Congress.gov became available for public interaction in September 2012. Learn more [About Congress.gov](https://www.congress.gov/about).

**Comment by JoshData** [comment]
I think the question is really whether pages like [http://www.thomas.gov/cgi-bin/bdquery/z?d114:h.r.00240:](http://www.thomas.gov/cgi-bin/bdquery/z?d114:h.r.00240:) will be archived.

**Comment by DanielSchuman** [comment]
My question was both -- general archiving of the landing pages as well as the specific pages for bills and other legislative info. I did not know about the THOMAS web archive (I had looked at places like the center for legislative archives but could not find it) and appreciate the info.

However, it would also be useful to have the older webpages available as well for each bill.

**Comment by jonquandt** [comment]
Closing - this request is several years old and is better addressed by the congress.gov team if it is still needed. 

It appear the thomas link above is being redirected to the congress.gov equivalent, though the leading `00`s in the bill are throwing it off a bit.
