### ISSUE TITLE
FDSYS site map out of sync with congress.gov

### ISSUE THREAD

**Issue by wcarter** [usgpo/bill-status#139]
The most recent hosue bill on congress.gov is HR 4225

 https://www.congress.gov/bill/116th-congress/house-bill/4225

But this bill and more is not reflected on:

https://www.govinfo.gov/sitemap/bulkdata/BILLSTATUS/116hr/sitemap.xml

**Comment by jonquandt** [comment]
Good afternoon,

That bill and others have been updated in the **govinfo** sitemaps. It looks like there were a large number of other packages queued up for sitemaps updates before the bulkdata ones were completed.

Please let us know if you see any other issues.

Just a note that you can also use the **govinfo** API to get a list of the most recently updated BILLSTATUS files. 

https://api.govinfo.gov/collections/BILLSTATUS/2019-09-03T00:00:00Z?offset=0&pageSize=100&api_key=DEMO_KEY

you can also limit this by congress.

https://api.govinfo.gov/collections/BILLSTATUS/2019-09-03T00:00:00Z?offset=0&pageSize=100&congress=116&api_key=DEMO_KEY

More information available at:
https://api.govinfo.gov/docs 

The bulkdata sitemaps are more straight-forward from a content retrieval perspective, since the xml link is directly on the page.

**Comment by llaplant** [comment]
Updated
https://www.govinfo.gov/bulkdata/BILLSTATUS/116/hr/BILLSTATUS-116hr4225.xml
<lastmod>2019-09-03T16:07:17.649Z</lastmod>
