### ISSUE TITLE
Bills since 23rd April not available yet

### ISSUE THREAD

**Issue by pavanbarve11** [usgpo/bill-status#238]
Hi, we do not see the following and many more bills from 4/23 in the XML file. Thanks!

https://www.congress.gov/bill/118th-congress/house-bill/8123?s=1&r=5
https://www.congress.gov/bill/118th-congress/house-bill/8124?s=1&r=4

**Comment by gpo-billstatus** [comment]
Available now.  Thanks.

From: Pavan Barve ***@***.***>
Sent: Tuesday, April 30, 2024 8:52 AM
To: usgpo/bill-status ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [External] [usgpo/bill-status] Bills since 23rd April not available yet (Issue #238)


CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.



Hi, we do not see the following and many more bills from 4/23 in the XML file. Thanks!

https://www.congress.gov/bill/118th-congress/house-bill/8123?s=1&r=5
https://www.congress.gov/bill/118th-congress/house-bill/8124?s=1&r=4

-
