### ISSUE TITLE
Missing committeeReports element

### ISSUE THREAD

**Issue by jhanna71** [usgpo/bill-status#246]
I noticed that Senate bills and some House bills that have committee reports with part numbers are missing the committeeReports element. Also in some cases the reported date in activities/item is different than the reported date in actions/items.

HRES1576 is correct.
https://www.govinfo.gov/bulkdata/BILLSTATUS/118/hres/BILLSTATUS-118hres1576.xml

<committeeReports>
<committeeReport>
<citation>H. Rept. 118-754</citation>
</committeeReport>
</committeeReports>

<activities>
<item>
<name>Reported original measure</name>
<date>2024-11-18T22:49:36Z</date>
</item>
</activities>

<actions>
<item>
<actionDate>2024-11-18</actionDate>
<text>The House Committee on Rules reported an original measure, H. Rept. 118-754, by Mrs. Fischbach.</text>
<type>Committee</type>
<actionCode>H12100</actionCode>
<sourceSystem>
<code>2</code>
<name>House floor actions</name>
</sourceSystem>
<committees>
<item>
<systemCode>hsru00</systemCode>
<name>Rules Committee</name>
</item>
</committees>
</item>

S465 has no committeeReports element and the wrong date in activities/item.
https://www.govinfo.gov/bulkdata/BILLSTATUS/118/s/BILLSTATUS-118s465.xml

<activities>
<item>
<name>Reported by</name>
<date>2024-11-19T00:35:36Z</date>
</item>

<item>
<actionDate>2024-11-18</actionDate>
<text>The House Committee on Rules reported an original measure, H. Rept. 118-754, by Mrs. Fischbach.</text>
<type>Committee</type>
<actionCode>5000</actionCode>
<sourceSystem>
<code>9</code>
<name>Library of Congress</name>
</sourceSystem>
<committees>
<item>
<systemCode>hsru00</systemCode>
<name>Rules Committee</name>
</item>
</committees>
</item>

HR5535 has no committeeReports element
https://www.govinfo.gov/bulkdata/BILLSTATUS/118/hr/BILLSTATUS-118hr5535.xml

<item>
<actionDate>2024-11-21</actionDate>
<text>Reported (Amended) by the Committee on Financial Services. H. Rept. 118-759, Part I.</text>
<type>Committee</type>
<actionCode>5000</actionCode>
<sourceSystem>
<code>9</code>
<name>Library of Congress</name>
</sourceSystem>
<committees>
<item>
<systemCode>hsba00</systemCode>
<name>Financial Services Committee</name>
</item>
</committees>
</item>

**Comment by jonquandt** [comment]
Good morning,

This appears to be because the upstream datasource (the congress.gov API) does not include that data as well - at least as of the time of this message.

For example:
[S. 465](https://api.congress.gov/v3/bill/118/s/465?format=xml&api_key=DEMO_KEY) does not have `committeeReports` elements

[H.Res 1576](https://api.congress.gov/v3/bill/118/hres/1576?format=xml&api_key=DEMO_KEY) does have those elements:

GovInfo pulls data from the congress.gov API to generate the BILLSTATUS and BILLSUM xml files. This will require a fix there before it is reflected in our XML. 

Once congress.go updates the data, it will be picked up by GovInfo in a few hours - we process updates multiple times a day for the current congress.

**Comment by jonquandt** [comment]
@jhanna71  - it appears that both of the reports above now have a committeeReports element. Please review and let me know if there is anything further.
