### ISSUE TITLE
Bill Summaries: Difference in data between Congress.gov & bulk data

### ISSUE THREAD

**Issue by dwillis** [usgpo/bill-status#5]
So congress.gov says the House passed this bill on April 18:

https://www.congress.gov/bill/114th-congress/house-bill/4570

Bill summary XML as of April 19 (mid-afternoon) doesn't have that:

https://www.gpo.gov/fdsys/bulkdata/BILLSTATUS/114/hr/BILLSTATUS-114hr4570.xml

Why would they be different?

**Comment by llaplant** [comment]
GPO retrieved information from Congress.gov at 4:04 AM on Tuesday, April 19th. Bill status information for 114hr4570 was updated on Congress.gov after 4:04 AM on Tuesday, April 19th. The update for BILLSTATUS-114hr4570.xml was made available after the job ran again at 4:00 AM on Wednesday April 20th.

**Comment by dwillis** [comment]
Gotcha, thanks.

**Comment by llaplant** [comment]
Starting Monday, we are going to run the update job at 8 AM instead of 4 AM. This should capture more of the early morning updates on Congress.gov. Regarding the sync, if we need to reprocess an entire Congress, it will take about a day. We are currently reprocessing data that has been updated on Congress.gov since April 1st. We are also reprocessing bill status files that contain House votes, and this should resolve issue #4

**Comment by dwillis** [comment]
That's great, thank you!
