### ISSUE TITLE
Bill Status actions questions

### ISSUE THREAD

**Issue by dwillis** [usgpo/bill-status#6]
Bill status files [like this one](https://www.gpo.gov/fdsys/bulkdata/BILLSTATUS/114/hr/BILLSTATUS-114hr4570.xml) contain nearly duplicative actions. For example:

![screen shot 2016-04-21 at 4 49 48 pm](https://cloud.githubusercontent.com/assets/2214/14723861/1e078dfe-07e1-11e6-91de-b7afc99a02fd.png)

The differences I can see occur in `actionCode` and sometimes in `sourceSystem`. Should we expect that a bill might have the same action, but with different actionCodes? Which one is considered canonical? Is one `sourceSystem` preferable to another?

Thanks!

**Comment by JoshData** [comment]
Relatedly, what logic does Congress.gov use to squash some redundant actions? Can we get a peak at the source code that handles that?

**Comment by wcarter** [comment]
Any further information on redundant actions? Did this get answered somewhere else and I missed it?

**Comment by 104PL104** [comment]
Yes, expect a bill to have the same action but with different actionCodes. Action Codes listed at https://www.congress.gov/help/field-values/action-codes, in general, condense detailed legislative action steps/"primary source data."

When House or Senate are the sourceSystem, understand those to be "primary source data." When LOC is the sourceSystem, consider that to be a data enhancement - intended to help provide meaningful context and supplement "primary source data."  

Various code sets are used by multiple systems in the House, Senate, and Library of Congress by legislative clerks and data editors for functions independent of this bulk data set. As new codes and systems have been developed (since the early 1970s), there was no coordinated effort to retroactively apply new codes to old records. Many codes are concatenated with other codes or elements or utilize free text. Codes in one set may be redundant with a different code in another code set. Additionally, some codes may have been used and re-used over the years for different purposes further complicating the ability to create an authoritative list. 

The Actions tab view options and Latest Action in the overview (see https://www.congress.gov/bill/114th-congress/house-bill/26/actions) show 4 different volumes of action information. Congress.gov serves multiple audiences

**Comment by MokeEire** [comment]
There also appears to be a set of action codes that do not correspond to any codes listed at https://www.congress.gov/help/field-values/action-codes e.g. `Intro-H`, `H11100`.

How would you suggest someone parses the distinct actions taken on a bill?

**Comment by 104PL104** [comment]
My suggestion is to focus on Action Codes, which are a controlled vocabulary. Action Codes were created to help machines, and people, have a consistent method to use for data from 1973-present. As we slowly move deeper into historical data we will use a subset of the same Action Codes.

[Action Codes](https://www.congress.gov/help/field-values/action-codes) identify stages that condense detailed [legislative action steps](https://www.congress.gov/help/legislative-glossary#glossary_legislativeaction).

Actions that do not have Action Codes should not be expected to be consistently used nor sufficiently unique.

**Comment by MokeEire** [comment]
What about action codes not listed in the table you linked? Should they be expected to be consistently used?

Of the top 10 action codes used in the 117th congress' data, only two are listed in that table.

![image](https://user-images.githubusercontent.com/19700454/164772056-e4836f64-86e6-48ee-9dac-4de864021317.png)
