### ISSUE TITLE
duplicate executive actions for HR 3731

### ISSUE THREAD

**Issue by wcarter** [usgpo/bill-status#92]
04/03/2018 | Became Public Law No: 115-160.
04/03/2018 | Became Public Law No: 115-160.
04/03/2018 | Signed by President.
04/03/2018 | Signed by President.

**Comment by wcarter** [comment]
this is happening with other recent public laws like S 2030 as well

**Comment by 104PL104** [comment]
Thank you for reporting this. We will delete the duplicates at the source, which should flow through to the Bulk Data later today.

FYI - Duplicates for executive actions do happen from time to time due to shared responsibility of both House and LOC to get these steps into our source systems as quickly as possible.

**Comment by wcarter** [comment]
looks good now.
